pipeline {
    agent any
    parameters {        
        string(
            name: 'PATH',
            description: 'gcs path',
            defaultValue: params.PATH ?: "gcs"
        )
        string(
            name: 'ENV',
            description: 'ennvironment',
            defaultValue: params.PATH ?: "dev"
        )
        string(
            name: 'PROJECT_ID',
            description: 'project',
            defaultValue: params.PATH ?: "dev-datalake"
        )
    }
    environment {

        GOOGLE_APPLICATION_CREDENTIALS = credentials("g_key")
        
    }
    stages {
        stage('Build env') {
            steps {
                script {
                    switch(params.ENV) {
                        case 'dev':                           
                            GCP_PROJECT_ID = params.PROJECT_ID                            
                            break
                        case 'stg':
                            GCP_PROJECT_ID = params.PROJECT_ID                            
                            break
                        default:
                            GCP_PROJECT_ID = params.PROJECT_ID       
                    }
                }
            }
        }
        stage('Build') {
            steps {      
                withEnv(['PATH+EXTRA=/usr/sbin:/usr/bin:/sbin:/bin']) {
                    sh """
                    pip3 install --upgrade google-cloud-storage
                    echo "${GCP_PROJECT_ID}"
                    echo "${params.PATH}"
                    python3 test.py ${params.PATH} ${GCP_PROJECT_ID}
                    """
                }        
            }
        }
        stage('Approval') {
            // no agent, so executors are not used up when waiting for approvals
            agent none
            steps {
                script {
                    input "Continue?"
                    echo 'Yes..'
                }
            }
        }
    }
}
